// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE1wBMzWcPxK0zozIhKfuBr0XXVR1TmWs',
    appId: '1:740761569305:web:e27185ed22810bb1520288',
    messagingSenderId: '740761569305',
    projectId: 'srocksmusic-ebd78',
    authDomain: 'srocksmusic-ebd78.firebaseapp.com',
    storageBucket: 'srocksmusic-ebd78.firebasestorage.app',
    measurementId: 'G-JM9ZZ8KF3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQpi5GCCLdzpB3TZlP1WX50XITWaYDyg',
    appId: '1:740761569305:android:b845440b975dcdc5520288',
    messagingSenderId: '740761569305',
    projectId: 'srocksmusic-ebd78',
    storageBucket: 'srocksmusic-ebd78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0F3eJOW4dg9xuEz_GU3o0xLQ41i3QPN8',
    appId: '1:740761569305:ios:553211fda9f62415520288',
    messagingSenderId: '740761569305',
    projectId: 'srocksmusic-ebd78',
    storageBucket: 'srocksmusic-ebd78.firebasestorage.app',
    iosBundleId: 'com.example.srocksMusicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0F3eJOW4dg9xuEz_GU3o0xLQ41i3QPN8',
    appId: '1:740761569305:ios:553211fda9f62415520288',
    messagingSenderId: '740761569305',
    projectId: 'srocksmusic-ebd78',
    storageBucket: 'srocksmusic-ebd78.firebasestorage.app',
    iosBundleId: 'com.example.srocksMusicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE1wBMzWcPxK0zozIhKfuBr0XXVR1TmWs',
    appId: '1:740761569305:web:d31730ebb5b0adca520288',
    messagingSenderId: '740761569305',
    projectId: 'srocksmusic-ebd78',
    authDomain: 'srocksmusic-ebd78.firebaseapp.com',
    storageBucket: 'srocksmusic-ebd78.firebasestorage.app',
    measurementId: 'G-4KQB3RXRSG',
  );

}